version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: configsettings-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespwd
      POSTGRES_DB: settingsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapi:
    build:
      context: ./ConfigSettings.WebApi
      dockerfile: Dockerfile
    container_name: configsettings-webapi
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Postgres=Host=postgres;Database=settingsdb;Username=postgres;Password=postgrespwd
      - Security__MasterKey=DevMasterKeyForDemoOnly123!
    ports:
      - "5000:5000"

volumes:
  pgdata:
